name: Run a yarn or npm command
description: Runs any yarn or npm command e.g. yarn test.
author: adzz
inputs:
  package-manager:
    description: Specify whether to use npm or yarn to run the tests. May be npm or yarn only defaults to yarn
    required: false
    default: yarn
  command:
    description: The command you wish to run e.g. test
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.package-manager }}
    - ${{ inputs.command }}
branding:
  icon: circle
  color: purple
